
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kalashnikov_estate_development
  username: <%= ENV["KALASHNIKOV_ESTATE_DATABASE_USERNAME"] %>
  password: <%= ENV["KALASHNIKOV_ESTATE_DATABASE_PASSWORD"] %>


test:
  <<: *default
  database: kalashnikov_estate_test
  username: <%= ENV["KALASHNIKOV_ESTATE_DATABASE_USERNAME"] %>
  password: <%= ENV["KALASHNIKOV_ESTATE_DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: kalashnikov_estate_production
  username: kalashnikov_estate
  password: <%= ENV["KALASHNIKOV_ESTATE_DATABASE_PASSWORD"] %>
