
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kalashnikov_estate_development
  username: <%= ENV["KALASHNIKOV_ESTATE_DATABASE_USERNAME_DEV"] %>
  password: <%= ENV["KALASHNIKOV_ESTATE_DATABASE_PASSWORD_DEV"] %>


test:
  <<: *default
  database: kalashnikov_estate_test
  username: <%= ENV["KALASHNIKOV_ESTATE_DATABASE_USERNAME_DEV"] %>
  password: <%= ENV["KALASHNIKOV_ESTATE_DATABASE_PASSWORD_DEV"] %>

production:
  <<: *default
  database: kalashnikov_estate_production
  username: <%= ENV["KALASHNIKOV_ESTATE_DATABASE_USERNAME"] %>
  password: <%= ENV["SECRET_KEY_BASE"] %>
  url: <%= ENV["DATABASE_URL"] %>